title: Pertiwi
subtitle: Food
content_is_about: # general content of website, used in footer menu title
show_logo: show # 'show' or 'hide'
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
keywords: template, static, smart, modular
lang: en_US
version: 0.0.1

baseurl: ""
url: "https://pertiwi.netlify.com"
qr: show # 'show' or 'hide' put qr.svg in includes/defs.html call it: icn--qr
menu: short_menu # 'short_menu' or 'long_menu'

company:
  name: Pertiwi
  legal_name: Amazing Food Ltd #if need to overrides 'company.name' in footer fill up this one
  email: info@email.com
  telephone: 800 12345678
  fax: 800 12345678
  address: Somerset House Strand, London WC2R 0RN, UK
  maplink: https://goo.gl/maps/NBkLEAwkHLF2
  country: Indonesia
  twitter: #
  facebook_page: #
  youtube: #
  instagram: #
  linkedin: #
  tripadvisor: #complete URL
  booking: #complete URL
  airbnb: #complete URL
  gplus: #
  tumblr: #
  soundcloud: #complete URL

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author: rokma
twitter:
  username: rokmatwit
facebook:
  app_id: #Facebook app ID for Facebook insights
  publisher: #Facebook page URL or ID of the publishing entity
  admins: #Facebook user ID for domain insights linked to a personal account
logo: /assets/favicons/apple-touch-icon-152x152.png
webmaster_verifications:
  google: google32e66f1a5601ec40


google:
  analytics: #

# Build settings
markdown: kramdown
plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer
exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - rokmama.gemspec
  - Gemfile
  - rakefile

permalink: /:title/ # pretty

collections:
  pages:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product # change this to get the layout needed
