title: Pertiwi Consulting
subtitle: Innovate for Sustainable Futures
content_is_about: # general content of website, used in footer menu title
show_logo: show # 'show' or 'hide'
description: > # this means to ignore newlines until "baseurl:"
  Innovate for Sustainable Futures
lang: en_US
version: 0.0.3

baseurl: ""
url: "https://pertiwi-consulting.com"

company:
  name: Pertiwi Consulting
  legal_name: PT. Bina Tjahaja Pertiwi #if need to overrides 'company.name' in footer fill up this one
  email: info@pertiwi-consulting.com
  telephone: +62 361 3005263
  fax: #
  address_line_1: Ibis Styles Business Complex Unit 3-4
  address_line_2: Jl. Teuku Umar No. 177, Denpasar
  address_line_3: 80114 Bali
  maplink: #
  country: Indonesia
  twitter: #
  facebook_page: #
  youtube: #
  instagram: #
  linkedin: #
  tripadvisor: #complete URL
  booking: #complete URL
  airbnb: #complete URL
  gplus: #
  tumblr: #
  soundcloud: #complete URL

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author: rokma
twitter:
  username: rokmatwit
facebook:
  app_id: #Facebook app ID for Facebook insights
  publisher: #Facebook page URL or ID of the publishing entity
  admins: #Facebook user ID for domain insights linked to a personal account
logo: /assets/favicons/apple-touch-icon-152x152.png
webmaster_verifications:
  google: google32e66f1a5601ec40


google:
  analytics: UA-112197787-1

# Build settings
markdown: kramdown
plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer
exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile

permalink: /:title/ # pretty
